apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-project
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris-project
  template:
    metadata:
      labels:
        app: tetris-project
    spec:
      containers:
      - name: tetris
        image: 540979843391.dkr.ecr.us-east-1.amazonaws.com/dockerimages:2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-service
  namespace: dev
spec:
  selector:
    app: tetris-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
